// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF5Cm0QS5f8BTnc3bnfQ6dJlywpAmpNxg',
    appId: '1:173047518882:web:d5138b0f58898fd9e3e9fb',
    messagingSenderId: '173047518882',
    projectId: 'auresia-notification',
    authDomain: 'auresia-notification.firebaseapp.com',
    storageBucket: 'auresia-notification.appspot.com',
    measurementId: 'G-2KN8LFD5SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBynxXYe5ZSu6qe9oFNYdKlsWiRZosAEgw',
    appId: '1:173047518882:android:8bfc68701a1018b8e3e9fb',
    messagingSenderId: '173047518882',
    projectId: 'auresia-notification',
    storageBucket: 'auresia-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmgo3Mm-HZWcz7cBpSTkaomEoXvkaXUKk',
    appId: '1:173047518882:ios:81938ac86ef7ea22e3e9fb',
    messagingSenderId: '173047518882',
    projectId: 'auresia-notification',
    storageBucket: 'auresia-notification.appspot.com',
    iosBundleId: 'edu.iu.jordan.strive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmgo3Mm-HZWcz7cBpSTkaomEoXvkaXUKk',
    appId: '1:173047518882:ios:8d7506c4d5c421f9e3e9fb',
    messagingSenderId: '173047518882',
    projectId: 'auresia-notification',
    storageBucket: 'auresia-notification.appspot.com',
    iosBundleId: 'com.example.strive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF5Cm0QS5f8BTnc3bnfQ6dJlywpAmpNxg',
    appId: '1:173047518882:web:ee4a08875e5e490be3e9fb',
    messagingSenderId: '173047518882',
    projectId: 'auresia-notification',
    authDomain: 'auresia-notification.firebaseapp.com',
    storageBucket: 'auresia-notification.appspot.com',
    measurementId: 'G-V43MJ1K8YF',
  );

}